// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;

namespace CsBindgen
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "libbencodex";

        [DllImport(__DllName, EntryPoint = "c_encode", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* c_encode(byte* input);

        [DllImport(__DllName, EntryPoint = "c_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void c_free(byte* str);

        [DllImport(__DllName, EntryPoint = "c_decode", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* c_decode(byte* input_bytes, nuint length);


    }



}
    